# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.1.0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Cache node_modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Resolve Dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
        
      - name: TypeCheck
        run: npm run typecheck
      
      - name: Build Check
        run: npm run build
